language: node_js
node_js:
- '0.11'
before_script:
- npm install -g grunt-cli
- git submodule update --init --recursive
- ./tasks/sauce/sauce_connect_setup.sh
- ./tasks/sauce/wait_for_browser_provider.sh
script:
- grunt test --saucelabs
env:
  global:
    - SAUCE_USERNAME=winjs
    - SAUCE_ACCESS_KEY=26c17025-4f79-4313-ab42-c5f77a7ece4b
branches:
  only:
    - master
    - /^.*-runut$/
